### ISSUE TITLE
Five files are missing for the GTOT dataset

### ISSUE THREAD

**Issue by xingchenzhang** [Alexadlu/DMCNet#1]
Hi,

Thank you very much for this wonderful work!

It seems that five files are missing in the results of the GTOT dataset. Could you please provide the 5 missing files?

Thank you!

Best wishes,
Xingchen

**Comment by Alexadlu** [comment]
Very sorry, I try to search 5 missed files but can not find them.
But you can directly execute main_drawresult.mat to obtain evaluation results with I provide .mat file, which is complete and true.
For .txt files, I'll rerun the results and upload them later when I have time.
Thanks for your attention.

**Comment by xingchenzhang** [comment]
> 

Hi,

Thank you very much! I have obtained the evaluation results using the .mat files.

Best wishes,
Xingchen
